### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by xuebaliang** [ChrisAllenMing/LtC-MSDA#3]
Hello, when I train the full model using "python train.py --use_target --save_model --target "mnistm" --checkpoint_dir "checkpoint"", I get the following error,
Traceback (most recent call last):
  File "train.py", line 114, in <module>
    main()
  File "train.py", line 105, in main
    num = solver.train_gcn_adapt(t, record_file=record_train)
  File "./LtC-MSDA/solver.py", line 348, in train_gcn_adapt
    loss.backward(retain_graph = True)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2048]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

However, though I set all "inplace=True" as "inplace=False", the error also occurs. Can you tell me how to deal with it? Thanks.

**Comment by JuhoLee95** [comment]
I have same problem.

**Comment by geonyeong-park** [comment]
Solved the same issue by downgrading torch version into 1.1.0
Usually such error comes out when the inplace operations x[0]=1 or x+=1 are included in wrong sense.

**Comment by webbrain-one** [comment]
Hi, thanks for reporting this. I opened PR #5 to fix this `RuntimeError`. It addresses the in-place tensor modification that interferes with autograd during `loss.backward(retain_graph=True)`, so training should proceed without the gradient computation error.
